spring.application.name=leave

spring.datasource.url=jdbc:postgresql://localhost:5432/leave_application
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8091

spring.jpa.hibernate.ddl_auto=create